package com.kickit.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.Date;

@DynamoDBTable(tableName = "EventDetails")
public class EventDetails {

    public EventDetails(){

    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String eventDetailId;

    String location;

    Date eventTime;


    public String getEventDetailId() {
        return eventDetailId;
    }

    public void setEventDetailId(String eventDetailId) {
        this.eventDetailId = eventDetailId;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public Date getEventTime() {
        return eventTime;
    }

    public void setEventTime(Date eventTime) {
        this.eventTime = eventTime;
    }
}
