package com.kickit.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import org.springframework.data.annotation.Id;

public class Event {

    @Id
    @DynamoDBAutoGeneratedKey
    private String eventId;

    private EventDetails eventDetails;
    private EventInvite eventInvite;
    private EventStatus eventStatus;

}
